package model;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.2.1.3.0.0914
public class EnseignantFacadeBeanServicePortClient {
    public static void main(String[] args) {
        EnseignantFacadeBeanService_Service enseignantFacadeBeanService_Service =
            new EnseignantFacadeBeanService_Service();
        EnseignantFacadeBeanService enseignantFacadeBeanService =
            enseignantFacadeBeanService_Service.getEnseignantFacadeBeanServicePort();
        // Add your code to call the desired methods.


    }
}
