
package model;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "EnseignantFacadeBeanService", targetNamespace = "http://model/",
                  wsdlLocation =
                  "http://localhost:7101/ProjetFinal-Model-webapp/EnseignantFacadeBeanService?WSDL#%7Bhttp%3A%2F%2Fmodel%2F%7DEnseignantFacadeBeanService")
public class EnseignantFacadeBeanService_Service extends Service {

    private final static URL ENSEIGNANTFACADEBEANSERVICE_WSDL_LOCATION;
    private final static WebServiceException ENSEIGNANTFACADEBEANSERVICE_EXCEPTION;
    private final static QName ENSEIGNANTFACADEBEANSERVICE_QNAME =
        new QName("http://model/", "EnseignantFacadeBeanService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("http://localhost:7101/ProjetFinal-Model-webapp/EnseignantFacadeBeanService?WSDL#%7Bhttp%3A%2F%2Fmodel%2F%7DEnseignantFacadeBeanService");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ENSEIGNANTFACADEBEANSERVICE_WSDL_LOCATION = url;
        ENSEIGNANTFACADEBEANSERVICE_EXCEPTION = e;
    }

    public EnseignantFacadeBeanService_Service() {
        super(__getWsdlLocation(), ENSEIGNANTFACADEBEANSERVICE_QNAME);
    }

    public EnseignantFacadeBeanService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ENSEIGNANTFACADEBEANSERVICE_QNAME, features);
    }

    public EnseignantFacadeBeanService_Service(URL wsdlLocation) {
        super(wsdlLocation, ENSEIGNANTFACADEBEANSERVICE_QNAME);
    }

    public EnseignantFacadeBeanService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ENSEIGNANTFACADEBEANSERVICE_QNAME, features);
    }

    public EnseignantFacadeBeanService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EnseignantFacadeBeanService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns EnseignantFacadeBeanService
     */
    @WebEndpoint(name = "EnseignantFacadeBeanServicePort")
    public EnseignantFacadeBeanService getEnseignantFacadeBeanServicePort() {
        return super.getPort(new QName("http://model/", "EnseignantFacadeBeanServicePort"),
                             EnseignantFacadeBeanService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EnseignantFacadeBeanService
     */
    @WebEndpoint(name = "EnseignantFacadeBeanServicePort")
    public EnseignantFacadeBeanService getEnseignantFacadeBeanServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://model/", "EnseignantFacadeBeanServicePort"),
                             EnseignantFacadeBeanService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ENSEIGNANTFACADEBEANSERVICE_EXCEPTION != null) {
            throw ENSEIGNANTFACADEBEANSERVICE_EXCEPTION;
        }
        return ENSEIGNANTFACADEBEANSERVICE_WSDL_LOCATION;
    }

}
